### ISSUE TITLE
Crash in Ehrenamtskarte

### ISSUE THREAD

**Issue by helllth** [cismet/carma#26]
When the Hamburger-Menu is opened the app crashes.

![Screenshot 2024-05-22 at 17 26 49](https://github.com/cismet/carma/assets/837211/e530b984-ad4d-472a-a238-ea15cac091f4)

**Comment by d4v3000** [comment]
![image](https://github.com/cismet/carma/assets/24357816/76987518-78e9-46a4-ac46-c940d342ce29)

Tested in a incognito window and a new browser and was able to open the menu now
