### ISSUE TITLE
The B-Plan Gazetteer is not searched

### ISSUE THREAD

**Issue by helllth** [cismet/carma#27]
![Screenshot 2024-05-22 at 17 27 49](https://github.com/cismet/carma/assets/837211/89f974f6-7597-48bd-ada7-78afc7945831)

**Comment by d4v3000** [comment]
![image](https://github.com/cismet/carma/assets/24357816/ab3f86c0-f839-4e2a-a88b-ad6c88387efd)

Added missing b-plaene to the gazetteer search

**Comment by d4v3000** [comment]
After checking the functionality on the original application again i have to reopen this issue. After selecting the bplan from the gazetteer it should select the corresponding bplan in the map

**Comment by d4v3000** [comment]
![image](https://github.com/cismet/carma/assets/24357816/9d713c55-532e-4b00-ac34-6e7604544950)

Now the searched bplan will be selected and shown on the map.
