### ISSUE TITLE
Doublecheck Gazetteer in FNP Inspektor

### ISSUE THREAD

**Issue by helllth** [cismet/carma#28]
1. Description Text is wrong
 
Original:
![Screenshot 2024-05-22 at 16 44 42](https://github.com/cismet/carma/assets/837211/e31825c1-ff02-48aa-84c0-1685fd5ae46e)

2. No results on BPlan or FNp ÄV (Check current Live App under: https://wunda-geoportal.cismet.de/#/fnp/rechtsplan?aevVisible&lat=51.25904336002396&lng=7.157835359327315&zoom=12)

![Screenshot 2024-05-22 at 17 29 47](https://github.com/cismet/carma/assets/837211/3da174a0-e1fe-4383-b804-ea76fd73abc9)

**Comment by d4v3000** [comment]
![image](https://github.com/cismet/carma/assets/24357816/b692f5bc-3db1-45dd-84ea-2f1f936a2725)

Changed the placeholder text & added the scale.
![image](https://github.com/cismet/carma/assets/24357816/061cbc92-5dff-4ff7-b549-95e2011cfd49)

Added search for B-Plaene & AEVs.

![image](https://github.com/cismet/carma/assets/24357816/99b1ca2e-8060-4c59-8134-f75d61fa7ec3)

Also added the feature selection after searching with the gazetteer.
